복잡한 행렬식은 파이썬 코드로 간단하게 처리할 수 있습니다!

In [ ]:
import tensorflow as tf

이것이 2x3 행렬을 코드로 표현한 것입니다

In [ ]:
x=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(x)
print(x.shape)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)


행렬의 덧셈

In [ ]:
j=tf.constant([1,2,3,4,5,6], shape=[2,3])
print(j)
k=tf.constant([7,8,9,10,11,12], shape=[2,3])
print(k)
l=tf.add(j,k)
print(l)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)


행렬의 곱셈

In [ ]:
a=tf.constant([1,2,3,4,5,6], shape=[2,3])
print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
b=tf.constant([7,8,9,10,11,12], shape=[3,2])
print(b)

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [ ]:
c=tf.matmul(a,b)
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


행렬의 나눗셈. 1/x을 계산하기

In [ ]:
x = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
print('x = ', x)
print()
y=tf.linalg.inv(x).numpy()
print('y = ', y)
print()
print('x 곱하기 y =', tf.matmul(x,y))


x =  tf.Tensor(
[[2. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)

y =  [[0.5 0. ]
 [0.  1. ]]

x 곱하기 y = tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
y=tf.constant([[1.0,0.0],[0.0, 1.0], [1.0, 0.0], [0.0, 1.0]])
print(y)
print(y.shape)

tf.Tensor(
[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]], shape=(4, 2), dtype=float32)
(4, 2)


In [ ]:
print(y.dtype)

<dtype: 'float32'>
